services:
  db:
    image: postgres:18
    container_name: bookify-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookify
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:

# Seed Tenant,TenantWorkingHours,TenantUsages,TenantSettings(use dfault for some of them), Subscription, Professionals, Customers, appointments (for next day tomorrow list try to have it full with a service created and well made)
# Check schema.prisma
