import { PrismaClient, PlanType, BillingCycle } from 'src/generated/prisma/client';
import { PlanCreateInput } from 'src/generated/prisma/models';

const plansData: PlanCreateInput[] = [
  {
    id: 'free',
    name: 'Plan Free',
    tagline: 'Empezá sin costo, organizá tus citas desde el día uno',
    description: 'Para profesionales que están comenzando',
    billingCycle: null,
    price: 0,
    compareAtPrice: null,
    trialDays: 0,
    isFeatured: false,
    sortOrder: 0,
    features: ['1 profesional', 'Reservas ilimitadas', 'Página de reservas', 'Estadísticas básicas', 'Sin recordatorios'],
    appointmentLimit: -1,
    emailLimit: 0,
    professionalLimit: 1,
    whatsappLimit: 0,
  },
  {
    id: 'pro_monthly',
    name: 'Plan Pro Mensual',
    tagline: 'Todo lo que necesitás para gestionar tu negocio solo',
    description: 'Para profesionales individuales',
    billingCycle: BillingCycle.MONTHLY,
    price: 14.99,
    compareAtPrice: null,
    trialDays: 14,
    isFeatured: false,
    sortOrder: 1,
    features: [
      'Todo lo del plan Free',
      'Recordatorios automáticos',
      'Estadísticas avanzadas',
      'Soporte prioritario',
      'Hasta 200 WhatsApp/mes',
      'Hasta 400 emails/mes',
    ],
    appointmentLimit: -1,
    emailLimit: 500,
    professionalLimit: 1,
    whatsappLimit: 200,
  },
  {
    id: 'pro_annual',
    name: 'Plan Pro Anual',
    tagline: 'Todo lo que necesitás para gestionar tu negocio solo',
    description: 'Para profesionales individuales',
    billingCycle: BillingCycle.ANNUAL,
    price: 143.88,
    compareAtPrice: 179.88,
    trialDays: 14,
    isFeatured: true,
    sortOrder: 1,
    features: [
      'Todo lo del plan Free',
      'Recordatorios automáticos',
      'Estadísticas avanzadas',
      'Soporte prioritario',
      'Hasta 200 WhatsApp/mes',
      'Hasta 400 emails/mes',
    ],
    appointmentLimit: -1,
    emailLimit: 500,
    professionalLimit: 1,
    whatsappLimit: 200,
  },
  {
    id: 'pro_plus_monthly',
    name: 'Plan Pro + Mensual',
    tagline: 'Todo lo que necesitás para gestionar tu negocio con equipo',
    description: 'Para profesionales individuales',
    billingCycle: BillingCycle.MONTHLY,
    price: 24.99,
    compareAtPrice: null,
    trialDays: 14,
    isFeatured: false,
    sortOrder: 2,
    features: [
      'Todo lo del plan Pro',
      'Hasta 5 profesionales',
      'Gestión de profesionales',
      'Panel de administración',
      'Hasta 1200 emails/mes',
      'Hasta 500 WhatsApp/mes',
    ],
    appointmentLimit: -1,
    emailLimit: 1200,
    professionalLimit: 5,
    whatsappLimit: 500,
  },
  {
    id: 'pro_plus_annual',
    name: 'Plan Pro + Anual',
    tagline: 'Todo lo que necesitás para gestionar tu negocio con equipo',
    description: 'Para profesionales individuales',
    billingCycle: BillingCycle.ANNUAL,
    price: 239.88,
    compareAtPrice: 299.88,
    trialDays: 14,
    isFeatured: false,
    sortOrder: 2,
    features: [
      'Todo lo del plan Pro',
      'Hasta 5 profesionales',
      'Gestión de profesionales',
      'Panel de administración',
      'Hasta 1200 emails/mes',
      'Hasta 500 WhatsApp/mes',
    ],
    appointmentLimit: -1,
    emailLimit: 1200,
    professionalLimit: 5,
    whatsappLimit: 500,
  },
];

export async function seedPlans(prisma: PrismaClient) {
  await prisma.plan.deleteMany({});

  await prisma.plan.createMany({
    data: plansData,
  });
}
