export enum VerificationType {
  EMAIL_CONFIRMATION = 'EMAIL_CONFIRMATION',
  PHONE_CONFIRMATION = 'PHONE_CONFIRMATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
  EMAIL_CHANGE = 'EMAIL_CHANGE',
  PHONE_CHANGE = 'PHONE_CHANGE',
}

export enum VerificationStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  EXPIRED = 'EXPIRED',
  LOCKED = 'LOCKED',
}

export enum LockReason {
  MAX_ATTEMPTS_EXCEEDED = 'MAX_ATTEMPTS_EXCEEDED',
  SUSPICIOUS_ACTIVITY = 'SUSPICIOUS_ACTIVITY',
  ADMIN_LOCKED = 'ADMIN_LOCKED',
}
