import { PERMISSIONS } from './permissions.constant';

export const ROLE_PERMISSIONS = {
  OWNER: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,
    PERMISSIONS.TENANT_DELETE,

    PERMISSIONS.BILLING_READ,
    PERMISSIONS.BILLING_MANAGE,

    PERMISSIONS.PROFESSIONAL_READ,
    PERMISSIONS.PROFESSIONAL_CREATE,
    PERMISSIONS.PROFESSIONAL_UPDATE,
    PERMISSIONS.PROFESSIONAL_UPDATE_SELF,
    PERMISSIONS.PROFESSIONAL_DELETE,

    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_INVITE,
    PERMISSIONS.TEAM_UPDATE,
    PERMISSIONS.TEAM_DELETE,

    PERMISSIONS.SERVICE_READ,
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.SERVICE_DELETE,

    PERMISSIONS.SCHEDULE_READ,
    PERMISSIONS.SCHEDULE_UPDATE,
    PERMISSIONS.SCHEDULE_UPDATE_SELF,
    PERMISSIONS.SCHEDULE_EXCEPTION_UPDATE,

    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.CUSTOMER_BLOCK,

    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_CREATE_OTHERS,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_DELETE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_CANCEL_OTHERS,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,
    PERMISSIONS.APPOINTMENT_READ_OTHERS,
    PERMISSIONS.APPOINTMENT_UPDATE_OTHERS,
    PERMISSIONS.APPOINTMENT_DELETE_OTHERS,
    PERMISSIONS.APPOINTMENT_RESCHEDULE_OTHERS,

    PERMISSIONS.REPORT_READ,
  ],

  ADMIN: [
    PERMISSIONS.TENANT_READ,
    PERMISSIONS.TENANT_UPDATE,

    PERMISSIONS.PROFESSIONAL_READ,
    PERMISSIONS.PROFESSIONAL_CREATE,
    PERMISSIONS.PROFESSIONAL_UPDATE,
    PERMISSIONS.PROFESSIONAL_UPDATE_SELF,
    PERMISSIONS.PROFESSIONAL_DELETE,

    PERMISSIONS.TEAM_READ,
    PERMISSIONS.TEAM_INVITE,
    PERMISSIONS.TEAM_UPDATE,
    PERMISSIONS.TEAM_DELETE,

    PERMISSIONS.SERVICE_READ,
    PERMISSIONS.SERVICE_CREATE,
    PERMISSIONS.SERVICE_UPDATE,
    PERMISSIONS.SERVICE_DELETE,

    PERMISSIONS.SCHEDULE_READ,
    PERMISSIONS.SCHEDULE_UPDATE,
    PERMISSIONS.SCHEDULE_UPDATE_SELF,
    PERMISSIONS.SCHEDULE_EXCEPTION_UPDATE,

    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,
    PERMISSIONS.CUSTOMER_UPDATE,
    PERMISSIONS.CUSTOMER_DELETE,
    PERMISSIONS.CUSTOMER_BLOCK,

    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_CREATE_OTHERS,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_DELETE,
    PERMISSIONS.APPOINTMENT_CANCEL,
    PERMISSIONS.APPOINTMENT_CANCEL_OTHERS,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,
    PERMISSIONS.APPOINTMENT_READ_OTHERS,
    PERMISSIONS.APPOINTMENT_UPDATE_OTHERS,
    PERMISSIONS.APPOINTMENT_DELETE_OTHERS,
    PERMISSIONS.APPOINTMENT_RESCHEDULE_OTHERS,

    PERMISSIONS.REPORT_READ,
  ],

  STAFF: [
    PERMISSIONS.APPOINTMENT_CANCEL,

    PERMISSIONS.SERVICE_READ,


    PERMISSIONS.CUSTOMER_READ,
    PERMISSIONS.CUSTOMER_CREATE,

    PERMISSIONS.APPOINTMENT_READ,
    PERMISSIONS.APPOINTMENT_CREATE,
    PERMISSIONS.APPOINTMENT_UPDATE,
    PERMISSIONS.APPOINTMENT_RESCHEDULE,
  ],
} as const;

export type Role = keyof typeof ROLE_PERMISSIONS;

export type Permission = (typeof ROLE_PERMISSIONS)[Role][number];
